/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_filez_jni_Blake3Jni */

#ifndef _Included_com_filez_jni_Blake3Jni
#define _Included_com_filez_jni_Blake3Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_filez_jni_Blake3Jni
 * Method:    nativeHashFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_filez_jni_Blake3Jni_nativeHashFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_filez_jni_Blake3Jni
 * Method:    nativeHashBytes
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_filez_jni_Blake3Jni_nativeHashBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_filez_jni_Blake3Jni
 * Method:    nativeHashFileStreaming
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_filez_jni_Blake3Jni_nativeHashFileStreaming
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
