/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_filez_jni_XxHash64Jni */

#ifndef _Included_com_filez_jni_XxHash64Jni
#define _Included_com_filez_jni_XxHash64Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_filez_jni_XxHash64Jni
 * Method:    nativeHashFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_filez_jni_XxHash64Jni_nativeHashFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_filez_jni_XxHash64Jni
 * Method:    nativeHashBytes
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_filez_jni_XxHash64Jni_nativeHashBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_filez_jni_XxHash64Jni
 * Method:    nativeHashFileWithSeed
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_filez_jni_XxHash64Jni_nativeHashFileWithSeed
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
